# Generated by Django 5.0.2 on 2024-02-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='has_permision_to_work',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='active',
            name='automatic',
            field=models.BooleanField(blank=True),
        ),
    ]
