# Generated by Django 5.0.1 on 2024-02-05 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('link_wavelength', models.FloatField()),
                ('pulsewidth', models.FloatField()),
                ('fiber_length', models.FloatField()),
                ('duration', models.FloatField()),
                ('link_number', models.FloatField()),
                ('test_number', models.FloatField()),
                ('test_manual', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ArrayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array_data', models.FloatField()),
                ('browse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.browser')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_id', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('link_number', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('browse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.browser')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_list', models.FloatField()),
                ('browse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.browser')),
            ],
        ),
        migrations.CreateModel(
            name='EventIndexPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_index_plot', models.FloatField()),
                ('browse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.browser')),
            ],
        ),
        migrations.CreateModel(
            name='EventLocationPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_location_print', models.FloatField()),
                ('browse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.browser')),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EndFiber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_id', models.CharField(max_length=255)),
                ('end_fiber', models.FloatField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.receiver')),
            ],
        ),
        migrations.AddField(
            model_name='browser',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.receiver'),
        ),
        migrations.CreateModel(
            name='SystemAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_id', models.CharField(max_length=255)),
                ('creation', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('severity', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('alarm_type', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('browse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.browser')),
            ],
        ),
        migrations.CreateModel(
            name='TableList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('types', models.CharField(max_length=100)),
                ('string_loc', models.FloatField()),
                ('loss', models.FloatField()),
                ('orl', models.FloatField()),
                ('att', models.FloatField()),
                ('section_loss', models.FloatField()),
                ('length_shift', models.FloatField()),
                ('browse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.browser')),
            ],
        ),
        migrations.CreateModel(
            name='XData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_data', models.FloatField()),
                ('browse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.browser')),
            ],
        ),
    ]
