# Generated by Django 5.0.3 on 2024-04-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arraydata',
            name='array_data_files',
        ),
        migrations.AlterField(
            model_name='arraydata',
            name='array_data',
            field=models.FileField(upload_to='array_data'),
        ),
    ]
